### ISSUE TITLE
Table size problem

### ISSUE THREAD

**Issue by juanpandiello** [Sarapulov/zignatures#3]
Dear Sarapulov.

I want to create a custom signature which include a table. The problem happen when I want to set the maxium size of the table.
The signature always resize like a responsive feature instead of respect the values set on the table.

I attached the example here

`<table style="width: 99px;">
    <tbody>
        <tr>
            <td style="width: 33px;">1</td>
            <td style="width: 33px;">2</td>
            <td style="width: 33px;">3</td>
        </tr>
    </tbody>
</table>`

![Captura de pantalla 2020-10-23 a las 11 38 46](https://user-images.githubusercontent.com/45873140/96988288-6dcba280-1524-11eb-98f3-1283aebdde62.png)

There is any way to fix this?

Thanks a lot

**Comment by Sarapulov** [comment]
Thanks for reporting.
Let me have a look and get back to you.

**Comment by Sarapulov** [comment]
I suppose you are trying to inject the table HTML directly in the App setting.
Which is how it supposed to work.
However, when you inject the HTML in that manner it is added to the ticket comment editor which sanitize it heavily. So if you will try to add custom styles that control your table width those will be removed.
The workaround here is to use the Dynamic Content. The HTML added using Dynamic Content is not sanitized. So it supports custom styles. Meaning you can:

1. Create Dynamic Content in Zendesk
2. Add there Table HTML with the styles that contol table width 
3. Inject Dynamic Content record into the App settings
4. Use it

I hope it helps.
I will mark this issue as resolved for now.
